### ISSUE TITLE
Can not create Ingress Controller

### ISSUE THREAD

**Issue by 53845714nF** [hasura/helm-charts#13]
Hello, I can't get the Ingress Controller to work. I'm on Docker Desktop on Windows with enabled Kubernetes. 
And I use the nginx Ingres Controller.

This is my  `values.yaml` File:

```
ingress:
  enabled: true
  hostName: "hasura.docker.internal"
  ingressClassName: "nginx"
  annotations: {}

postgres:
  enabled: true

  auth:
    username: postgres
    password: postgrespassword
    database: postgres

  persistence:
    enabled: true
    size: 1Gi

secret:
  adminSecret: "my-secret"
  jwtSecret: {"type": "HS256", "key": "this-is-a-generic-HS256-secret-key-and-you-should-really-change-it"}
  unauthorizedRole: "anonymous"
  extraSecrets:
    DATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres

extraEnvs:
  - name: JWT_URL
    value: http://hasura-jwt:3000
```

The following command was used: `helm upgrade hasura -f ./values.yaml hasura/hasura-enterprise-stack`

I also tried to add my own Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hasura.docker.internal
      http:
        paths:
          - path: /
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: hasura-graphql-engine
                port:
                  number: 8080
```
With this, I'm able to get the Hasura login site, but then I get 401 Unauthorized Error after login.
